spring:
  cloud:
    stream:
      function:
        definition: attendEventSubscriber;
      bindings:
        attendEventSubscriber-in-0:
          destination: attend-event
server:
  port: 8082

grasstudy:
  google:
    credentials: ${GOOGLE_APPLICATION_CREDENTIALS}