spring:
  cloud:
    stream:
      function:
        definition: studyCreateEventPublisher;studyJoinEventPublisher;
      bindings:
        studyCreateEventPublisher-out-0:
          destination: study-create-event
        studyJoinEventPublisher-out-0:
          destination: study-join-event
server:
  port: 8081