spring:
  cloud:
    stream:
      function:
        definition: studyCreateEventPublisher;attendRequestEventPublisher;keyCreateEventSubscriber;
      bindings:
        studyCreateEventPublisher-out-0:
          destination: study-create-event
        attendRequestEventPublisher-out-0:
          destination: attend-request-event
        keyCreateEventSubscriber-in-0:
          destination: signkey-create-event
server:
  port: 8081