spring:
  cloud:
    stream:
      function:
        definition: studyCreateEventPublisher;attendEventPublisher;keyCreateEventSubscriber;
      bindings:
        studyCreateEventPublisher-out-0:
          destination: study-create-event
        attendEventPublisher-out-0:
          destination: attend-event
        keyCreateEventSubscriber-in-0:
          destination: signkey-create-event
server:
  port: 8081