name: member-service-CI/CD

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          architecture: x64
      - name: Test & Build With Maven
        run: mvn clean package -Dmaven.test.skip=false -f pom.xml
      - name: Deploy Service
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "target/group-*.jar"
          target: ${{ secrets.SERVICE_PATH }}
          strip_components: 1
      - name: Restrat Service
        uses: appleboy/ssh-action@v0.1.6
        env:
          SCRIPT_DIR: ${{ secrets.SERVICE_PATH }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: SCRIPT_DIR
          script: |
            cd  $SCRIPT_DIR
            sh ./stop.group-service.sh
            sh ./start.group-service.sh